[package]
name = "kahawai-media"
version.workspace = true
edition.workspace = true

[dependencies]
kahawai-core = { workspace = true }
anyhow = { workspace = true }
gstreamer = { workspace = true }
gstreamer-pbutils = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
gstreamer-app = "0.25.2"

