[package]
name = "kahawai-media"
version.workspace = true
edition.workspace = true

[dependencies]
kahawai-core = { workspace = true }
anyhow = { workspace = true }
gstreamer = { workspace = true }
gstreamer-pbutils = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
