[package]
name = "kahawai-mediahost"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
md4 = { workspace = true }
crc32fast = { workspace = true }
kahawai-core = { workspace = true }
kahawai-intro = { workspace = true }
kahawai-media = { workspace = true }
kahawai-proto = { workspace = true }
kahawai-transport = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
rustls = { workspace = true }
walkdir = { workspace = true }
xxhash-rust = { workspace = true }
notify = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
gstreamer = { workspace = true }
