[package]
name = "kahawai-hub"
version.workspace = true
edition.workspace = true

[dependencies]
kahawai-core = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rcgen = { workspace = true }
x509-parser = { workspace = true }
sha2 = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
