[package]
name = "kahawai-hub"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kahawai-core = { workspace = true }
kahawai-media = { workspace = true }
kahawai-proto = { workspace = true }
kahawai-transport = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
rcgen = { workspace = true }
x509-parser = { workspace = true }
sha2 = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ulid = { workspace = true }
bytes = "1"
xxhash-rust = { workspace = true }
reqwest = { workspace = true }
roxmltree = { workspace = true }
flate2 = { workspace = true }
md-5 = { workspace = true }
aes = { workspace = true }
async-trait = { workspace = true }
unicode-normalization = "0.1"
rust-embed = { workspace = true }
argon2 = "0.5.3"
rand_core = { version = "0.6", features = ["std"] }
jsonwebtoken = { version = "10.4.0", default-features = false, features = ["rust_crypto"] }

[dev-dependencies]
tracing-subscriber = { workspace = true }
kahawai-transcoder = { workspace = true }
tempfile = { workspace = true }
tower = { workspace = true, features = ["util"] }
kahawai-mediahost = { workspace = true }
